spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/Brsyrdkl/config-server-rent-a-car
server:
  port: 8888

